### ISSUE TITLE
Redis may not be used as cache, why not provide a global redis resource manager?

### ISSUE THREAD

**Issue by snowwolf007cn** [zendframework/zend-cache#121]
We may not use redis just as a cache storage, but also a db backend. So why not provide redis resource as a global redis resource manager?

**Comment by marc-mabe** [comment]
Hi,

The resource managers are available in zend-cache just because this component requires the resources to work and to make recourses reusable over different cache instances as zend-cache is designed to have one instance per item type.

You can of course use the resource manager also as global and you can also inject an existing resource into it.

Btw. I have opened a ticket some time ago to fully remove the resource managers, move this logic to somewhere else (like service manager) and let zend-cache injection the resources directly. But this is not well discussed until now.

**Comment by marc-mabe** [comment]
See #24

**Comment by snowwolf007cn** [comment]
I found the bitcount and bitop, that's what I need.

**Comment by marc-mabe** [comment]
I'm closing this now as the main ticket is #24
