### ISSUE TITLE
PSR-16 support: prevent concurrent regression when calling delete

### ISSUE THREAD

**Issue by weierophinney** [zendframework/zend-cache#158]
Per [a comment](https://github.com/zendframework/zend-cache/pull/152#issuecomment-383011006) by @marc-mabe : 

> on delete there is a concurrent regression. You first check for existence and then delete but the item could be added between both calls. As removeItem return true/false based of if the item was deleted it will throw an error only in case the deletion of an existing item failed. So probably just ignoring the return value and return true in all cases

**Comment by thomasvargiu** [comment]
As @marc-mabe suggested, I think should be better to return `true` in any case. Adapters throws exceptions on failure, that is handled by the try/catch block.

**Comment by thomasvargiu** [comment]
From a [comment](https://github.com/zendframework/zend-cache/pull/160#issuecomment-383732982) in #160:

> Another thing to think about is that some adapters have the same problem described in #158 (Dba and Filesystem at least).
The only concurrent regression that will result in a problem is not when a key is added between the two calls (hasItem() and removeItem()), but when a key exists and then it's removed between the two calls, returning false instead of true. We don't mind if an item is added after hasItem() because the beahvior will be the same calling directly removeItem() I think.

**Comment by weierophinney** [comment]
Fixed with #163
