### ISSUE TITLE
PSR-16 and blackhole not possible

### ISSUE THREAD

**Issue by dol** [zendframework/zend-cache#169]
I'd like to use the blackhole storage in combination with the PSR-16 decorator. But this is not possible because the blackhole doesn't support plugins.

### Code to reproduce the issue
```sh
 composer require zendframework/ze
```

```php
<?php

require_once __DIR__ . '/vendor/autoload.php';

use Zend\Cache\StorageFactory;
use Zend\Cache\Psr\SimpleCache\SimpleCacheDecorator;

try {
  $cache = StorageFactory::factory([
      'adapter' => 'blackhole',
      'plugins' => ['serializer'],
  ]);
} catch (Exception $e) {
  echo 'Error: ', $e->getMessage(), "\n";
}

try {
  $storage  = StorageFactory::adapterFactory('blackhole');
  $cache = new SimpleCacheDecorator($storage);
} catch (Exception $e) {
  echo 'Error: ', $e->getMessage(), "\n";
}

//$storage  = StorageFactory::adapterFactory('blackhole');
// $plugin = StorageFactory::pluginFactory('serializer');
// $cache->addPlugin($plugin);

```

### Expected results
Loading of class.

### Actual results
```
Error: The adapter 'Zend\Cache\Storage\Adapter\BlackHole' doesn't implement 'Zend\EventManager\EventsCapableInterface' and therefore can't handle plugins
Error: The storage adapter "Zend\Cache\Storage\Adapter\BlackHole" requires a serializer plugin; please see https://docs.zendframework.com/zend-cache/storage/plugin/#quick-start for details on how to attach the plugin to your adapter.
```

**Comment by weierophinney** [comment]
When I was finalizing PSR-16 support, I found that this adapter couldn't be coerced into behaving in the way that PSR-16 expects, which is why no support was provided for it.

If you want similar functionality, you can create either a named or an anonymous class that directly implements the PSR-16 interface, and have each method be a no-op and/or return a default.

**Comment by nuxwin** [comment]
@weierophinney 

In fact, both PSR6 and PSR16 caching wrappers are not compatible with the BlackHole adapter in fact. Well, this is a bit sad as for instance, in our application, we make use of the BlackHole adapter when we are in development mode... Since the BlackHole adapter is just something which will always return false, I'm wondering why it couldn't just lie on the supported types. This would avoid requiring serializer plugin and make it compatible with PSR* wrappers. What would be the side effect  here since that adapter always return false anyway?

**Comment by weierophinney** [comment]
@nuxwin If you can find a way to make it happen, I'd be happy to review a pull request! (I tried a number of approaches, but never found one that would pass tests.)

**Comment by nuxwin** [comment]
@weierophinney 

Don't be so rude (dixit your exclamation mark). I don't say you're wrong in any way ;) I just say I don't understand why you could not just lie on the adapter capabilities. Anyway, I turned to just disable read/write of the apcu adapter in development mode.

**Comment by weierophinney** [comment]
Wasn't intending to be rude, @nuxwin - should have put a :smile: after that! Honestly would love to see a PR to make this work properly.

**Comment by dol** [comment]
https://www.fastcompany.com/3036748/why-its-so-hard-to-detect-emotion-in-emails-and-texts ;-)
